# Generated by Django 3.2.25 on 2025-08-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
