# Generated by Django 3.2.25 on 2025-08-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0003_alter_script_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='param_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
