# Generated by Django 3.2.25 on 2025-08-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0004_script_param_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_type',
            field=models.CharField(default='python3', max_length=50),
        ),
    ]
