# Generated by Django 3.2.25 on 2025-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0005_script_script_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='exec_cmd',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
